SRC += main.c

LIBS += MdePkg/BaseDebugPrintErrorLevelLib.lib
LIBS += MdePkg/BaseLib.lib
LIBS += MdePkg/BasePcdLibNull.lib
LIBS += MdePkg/BasePrintLib.lib
LIBS += MdePkg/UefiApplicationEntryPoint.lib
LIBS += MdePkg/UefiBootServicesTableLib.lib
LIBS += MdePkg/UefiDebugLibConOut.lib
LIBS += MdePkg/UefiDevicePathLib.lib
LIBS += MdePkg/UefiMemoryAllocationLib.lib
LIBS += MdePkg/UefiMemoryLib.lib
LIBS += MdePkg/UefiRuntimeServicesTableLib.lib
LIBS += MdePkg/UefiLib.lib

NAME = example

M=$(PWD)

include ../Makefile
