SRC += main.c

LIBS += MdePkg/BaseDebugPrintErrorLevelLib.a
LIBS += MdePkg/BaseLib.a
LIBS += MdePkg/BasePcdLibNull.a
LIBS += MdePkg/BasePrintLib.a
LIBS += MdePkg/UefiApplicationEntryPoint.a
LIBS += MdePkg/UefiBootServicesTableLib.a
LIBS += MdePkg/UefiDebugLibConOut.a
LIBS += MdePkg/UefiDevicePathLib.a
LIBS += MdePkg/UefiMemoryAllocationLib.a
LIBS += MdePkg/UefiMemoryLib.a
LIBS += MdePkg/UefiRuntimeServicesTableLib.a
LIBS += MdePkg/UefiLib.a

NAME = example

M=$(PWD)

include ../Makefile
